// CurrentAddress
export const UPDATE_CURRENT_ADDRESS = 'UPDATE_CURRENT_ADDRESS'

//Initial Location Updates
export const INITIAL_LAT = 'INITIAL_LAT'
export const INITIAL_LNG = 'INITIAL_LNG'
export const INITIAL_REGION = 'INITIAL_REGION'

//Register
export const UPDATE_PHONE_NUMBER = 'UPDATE_PHONE_NUMBER'
export const UPDATE_PHONE_WITH_CODE = 'UPDATE_PHONE_WITH_CODE'
export const UPDATE_COUNTRY_CODE = 'UPDATE_COUNTRY_CODE'
export const UPDATE_FIRST_NAME = 'UPDATE_FIRST_NAME'
export const UPDATE_LAST_NAME = 'UPDATE_LAST_NAME'
export const UPDATE_EMAIL = 'UPDATE_EMAIL' 

//Paypal Status
export const PAYPAL_PAYMENT_STATUS = 'PAYPAL_PAYMENT_STATUS' 
